POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "luapdever",
  "email": "luapdever511@gmail.com",
  "password": "mdppaul"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ademonlasnn@gmail.com",
  "password": "illuminatie"
}
###
GET http://localhost:5000/api/private
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGI3Yjc3ZjRmZTRjYzdjN2E1ZTlmOSIsImlhdCI6MTY0Mjc5MTczOCwiZXhwIjoxNjQyNzkyMzM4fQ.CdClQbIOGrFAb-qedyMrmRddniCu4XlkwIECL84TBsc

###
POST http://localhost:5000/api/auth/forgotpassword
Content-Type: application/json

{
  "email": "luapdever511@gmail.com"
}
###
PUT http://localhost:5000/api/auth/resetpassword/c63a1226acbd47b7326927caaa2581a91943aac4
Content-Type: application/json

{
  "password": "mdppaul"
}

###
GET http://localhost:5000/api/users
###
GET http://localhost:5000/api/user/61db25f23d1a5163dadc3df4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGI3Yjc3ZjRmZTRjYzdjN2E1ZTlmOSIsImlhdCI6MTY0Mjc5MTczOCwiZXhwIjoxNjQyNzkyMzM4fQ.CdClQbIOGrFAb-qedyMrmRddniCu4XlkwIECL84TBsc
###
GET http://localhost:5000/api/products
###
GET http://localhost:5000/api/products/65eze
###
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "productName": "Riopop",
  "description": "Soft rlimits too low",
  "price": 5000,
}
